
trigger:
  branches:
    include:
      - master
      - feature/*

pr:
  branches:
    include:
      - master
      - feature/*

pool:
  vmImage: 'ubuntu-22.04'

variables:
  GO111MODULE: 'on'
  GOPROXY: 'https://proxy.golang.org'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    sudo apt-get update
    sudo apt-get install -y \
      build-essential \
      golang-go \
    pip install semgrep
  displayName: 'Install dependencies'

- script: |
    go version
    python3 --version
    semgrep --version
  displayName: 'Verify environment'

- script: |
    cd sonic-gnmi-standalone
    echo "Running Continuous Integration checks..."
    ## echo "Hint: you can also run these locally..."
    make ci
  displayName: 'Run CI pipeline'
